[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
arithmetic = { path = "../arithmetic" }
blake3 = "1.3"
rs_merkle = "1.3"