[package]
name = "poly_commit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arithmetic = { path = "../arithmetic" }
util = { path = "../util" }
rand = "0.8.5"
rs_merkle = "1.3"